name: "Test tutorial documentation with Spread"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "docs/tutorial.md"

jobs:
  tutorial-spread-test:
    uses: canonical/charm-ci/.github/workflows/integration-test.yml@14b1cf49d48b9d5b96192d9bca2890c98b7295cf # v1.0.2
    secrets: inherit
    permissions:
      contents: read
      packages: write
      actions: read
    with:
      working-directory: .
      spread-jobs-include: "*tests/spread/tutorial*"
